import path from 'path';
import consola from 'consola';
import fs from 'fs-extra';
import * as esbuild from 'esbuild';
import { packages, rootDir, readRootVersion } from './utils.js';

type ReleaseEntry = {
  /** module specifier */
  spec: string;
  /** absolute file path */
  absPath: string;
};

async function resolveDistEntry(pkgDir: string): Promise<string> {
  const distDir = path.join(pkgDir, 'dist');
  const entryMjs = path.join(distDir, 'index.mjs');
  const entryJs = path.join(distDir, 'index.js');

  if (await fs.pathExists(entryMjs)) return entryMjs;
  if (await fs.pathExists(entryJs)) return entryJs;

  throw new Error(`dist entry not found: ${pkgDir} (expected dist/index.mjs or dist/index.js)`);
}

async function createReleaseReadme(version: string) {
  return `# grafana-fast release bundle

版本：${version}

该目录用于“**不通过 npm 安装 @grafana-fast/* 包**”的分发形态：你可以把整个 \`release/\` 文件夹复制到任何宿主项目中，
宿主项目只需要提供必要的 peer dependencies，然后直接 import \`release/index.mjs\` 即可使用 \`useDashboardSdk\`。

## 你需要复制哪些文件？

复制整个 \`release/\` 文件夹即可（推荐放到宿主项目的 \`src/vendor/grafana-fast/\` 或类似目录）。

## 宿主项目需要安装的依赖（peer deps）

> 注意：Vue 必须由宿主提供（不能内置），否则会出现“Ref / watch 不互通”的问题。

\`\`\`bash
pnpm add vue echarts @ant-design/icons-vue
\`\`\`

## 使用方式

\`\`\`ts
import { ref } from 'vue';
import { useDashboardSdk } from './vendor/grafana-fast/index.mjs';

const containerRef = ref<HTMLElement | null>(null);

const sdk = useDashboardSdk(containerRef, {
  // 远程模式：宿主自行提供 apiClient + getDashboardSessionKey
  // apiClient: yourApiClient,
  // getDashboardSessionKey: async () => '...',
});
\`\`\`

### 样式（必须）

\`release/index.mjs\` 已默认 \`import './style.css'\`（适用于 Vite/Webpack 等构建工具）。
如果你的构建链不支持从 JS import CSS，请在入口手动引入：

\`\`\`ts
import './vendor/grafana-fast/style.css';
\`\`\`

## 可选：使用内置 mock（本地演示）

该目录额外提供 \`mock.mjs\`（等价于 \`@grafana-fast/api/mock\`），仅用于本地演示/回归：

\`\`\`ts
const { createMockApiClient } = await import('./vendor/grafana-fast/mock.mjs');
const api = createMockApiClient();
\`\`\`
`;
}

function transformHookTypesToStandalone(raw: string) {
  const lines = raw.split(/\r?\n/);
  const out: string[] = [];
  for (const line of lines) {
    if (line.includes("from '@grafana-fast/api'")) continue;
    if (line.includes("from '@grafana-fast/dashboard'")) continue;
    if (line.includes("from '@grafana-fast/types'")) continue;
    out.push(line);
  }

  const injected: string[] = [];
  injected.push('// NOTE: This file is generated by scripts/pack-dist.ts (release bundle types).');
  injected.push('// It intentionally avoids any `@grafana-fast/*` type imports so consumers can use it without pnpm add.');
  injected.push('type ID = string;');
  injected.push('type Timestamp = number;');
  injected.push('interface TimeRange { from: string | Timestamp; to: string | Timestamp; }');
  injected.push("type DashboardTheme = 'light' | 'dark';");
  injected.push("type DashboardThemePreference = DashboardTheme | 'system';");
  injected.push('type GrafanaFastApiClient = any;');

  const merged = out.join('\n').replace(
    /type DashboardApi = HttpApiEndpointKey;/g,
    'type DashboardApi = (typeof DashboardApi)[keyof typeof DashboardApi];'
  );

  const marker = "import { Ref } from 'vue';";
  if (!merged.includes(marker)) {
    throw new Error('Unexpected hook dist d.ts shape: missing vue Ref import.');
  }

  const withInjection = merged.replace(marker, `${marker}\n\n${injected.join('\n')}`);

  if (/from '@grafana-fast\//.test(withInjection)) {
    throw new Error('Release types should not contain any @grafana-fast/* import statements.');
  }

  return withInjection.trimEnd() + '\n';
}

async function buildReleaseBundle(
  entries: ReleaseEntry[],
  outFile: string,
  external: string[],
  options: { bannerCssImport?: boolean } = {}
) {
  const table = new Map(entries.map((e) => [e.spec, e.absPath]));

  const aliasPlugin: esbuild.Plugin = {
    name: 'grafana-fast-dist-alias',
    setup(build) {
      build.onResolve({ filter: /^@grafana-fast\// }, (args) => {
        const direct = table.get(args.path);
        if (direct) return { path: direct };
        return null;
      });
    },
  };

  await esbuild.build({
    entryPoints: [entries[0].absPath],
    outfile: outFile,
    format: 'esm',
    platform: 'browser',
    bundle: true,
    splitting: false,
    treeShaking: true,
    target: 'es2020',
    external,
    minify: true,
    legalComments: 'none',
    ...(options.bannerCssImport
      ? {
          banner: {
            js: `import './style.css';\n`,
          },
        }
      : {}),
    plugins: [aliasPlugin],
  });
}

async function main() {
  const version = await readRootVersion();
  const outDir = path.join(rootDir, 'release');

  consola.start(`生成 release bundle（输出目录：${outDir}）`);
  await fs.remove(outDir);
  await fs.ensureDir(outDir);

  await fs.writeFile(path.join(outDir, 'README.md'), await createReleaseReadme(version), 'utf8');

  const hookPkg = packages.find((p) => p.name === '@grafana-fast/hooks');
  if (!hookPkg) throw new Error('Cannot find @grafana-fast/hooks in meta package list.');

  // 1) index.mjs: bundle hook + internal deps into a single file (host provides peer deps)
  const internalEntries: ReleaseEntry[] = [];
  for (const pkg of packages) {
    const abs = await resolveDistEntry(pkg.dir);
    internalEntries.push({ spec: pkg.name, absPath: abs });

    // Optional subpath exports for demo convenience
    if (pkg.name === '@grafana-fast/api') {
      const mock = path.join(pkg.dir, 'dist', 'mock.mjs');
      if (await fs.pathExists(mock)) internalEntries.push({ spec: '@grafana-fast/api/mock', absPath: mock });
    }
    if (pkg.name === '@grafana-fast/component') {
      const styles = path.join(pkg.dir, 'dist', 'styles.mjs');
      if (await fs.pathExists(styles)) internalEntries.push({ spec: '@grafana-fast/component/styles', absPath: styles });
    }
  }

  const hookEntry = internalEntries.find((e) => e.spec === '@grafana-fast/hooks');
  if (!hookEntry) throw new Error('Cannot resolve dist entry for @grafana-fast/hooks.');

  consola.start(`bundle SDK: ${hookEntry.spec} -> release/index.mjs`);
  await buildReleaseBundle([hookEntry, ...internalEntries], path.join(outDir, 'index.mjs'), [
    // peer deps: must be provided by host app (same Vue instance!)
    'vue',
    'echarts',
    '@ant-design/icons-vue',
  ], { bannerCssImport: true });
  consola.success('OK: release/index.mjs');

  // 2) Optional: mock entry for local demo (equivalent to @grafana-fast/api/mock)
  const apiMock = internalEntries.find((e) => e.spec === '@grafana-fast/api/mock');
  if (apiMock) {
    consola.start(`bundle mock: ${apiMock.spec} -> release/mock.mjs`);
    await buildReleaseBundle([apiMock, ...internalEntries], path.join(outDir, 'mock.mjs'), []);
    consola.success('OK: release/mock.mjs');
  } else {
    consola.warn('Skip release/mock.mjs (dist/mock.mjs not found).');
  }

  // 3) index.d.ts: standalone types (no @grafana-fast/* imports)
  const hookTypesPath = path.join(hookPkg.dir, 'dist', 'index.d.ts');
  if (!(await fs.pathExists(hookTypesPath))) {
    throw new Error(`hook types not found: ${hookTypesPath}`);
  }
  const hookTypesRaw = await fs.readFile(hookTypesPath, 'utf8');
  const types = transformHookTypesToStandalone(hookTypesRaw);
  await fs.writeFile(path.join(outDir, 'index.d.ts'), types, 'utf8');
  // TS consumers may import `./index.mjs`; provide `.d.mts` for better NodeNext resolution.
  await fs.writeFile(path.join(outDir, 'index.d.mts'), types, 'utf8');

  // 4) Optional: mock.d.ts (minimal)
  if (apiMock) {
    const mockTypes = `// NOTE: This file is generated by scripts/pack-dist.ts (release mock types).\nexport declare function createMockApiClient(): any;\n`;
    await fs.writeFile(path.join(outDir, 'mock.d.ts'), mockTypes, 'utf8');
    await fs.writeFile(path.join(outDir, 'mock.d.mts'), mockTypes, 'utf8');
  }

  // 5) style.css: merge extracted CSS from internal packages + esbuild-generated CSS
  const cssFiles = [
    path.join(rootDir, 'packages/component/dist/component.css'),
    path.join(rootDir, 'packages/dashboard/dist/dashboard.css'),
  ];
  let css = `/* grafana-fast release styles (v${version}) */\n`;
  for (const file of cssFiles) {
    if (await fs.pathExists(file)) {
      css += `\n/* source: ${path.relative(rootDir, file)} */\n`;
      css += await fs.readFile(file, 'utf8');
      css += '\n';
    } else {
      consola.warn(`CSS file not found (skipped): ${file}`);
    }
  }

  // esbuild extracts CSS imports into standalone `.css` files (e.g. vue-grid-layout styles).
  // Merge them into a single `style.css` to keep the release folder easy to copy/use.
  const releaseEntries = await fs.readdir(outDir, { withFileTypes: true });
  const extractedCssFiles = releaseEntries
    .filter((e) => e.isFile() && e.name.endsWith('.css') && e.name !== 'style.css')
    .map((e) => path.join(outDir, e.name))
    .sort();

  for (const file of extractedCssFiles) {
    css += `\n/* source: ${path.relative(outDir, file)} (esbuild extracted) */\n`;
    css += await fs.readFile(file, 'utf8');
    css += '\n';
  }

  await fs.writeFile(path.join(outDir, 'style.css'), css, 'utf8');

  // Remove extracted css artifacts so consumers only need to care about `style.css`.
  for (const file of extractedCssFiles) {
    await fs.remove(file);
  }

  consola.success(`release bundle 产物已生成：${outDir}`);
}

main().catch((error) => {
  consola.error(error);
  process.exit(1);
});
